### ISSUE TITLE
Errors while using with ember-handlebars

### ISSUE THREAD

**Issue by kay-is** [lazd/gulp-handlebars#41]
The docs say I should use `ember-handlebars` for Ember templates, but it seems this package isn't maintained anymore.
When I use the `gulp-handlebars` without `ember-handlebars` I get

```
Uncaught TypeError: Cannot set property 'currentViewBinding' of undefined
```

When I use it with ember-handlebars I get

```
Unknown template object: function
```

**Comment by mattma** [comment]
@jonkemp @ringmaster 

I believe this [PR](https://github.com/lazd/gulp-handlebars/pull/44) should fix the problem that you guys have. It would be merged into master anytime soon.

At the same time, you could definite the path in your `package.json` from my [fork](https://github.com/mattma/gulp-handlebars). and check out the [newly added example](https://github.com/mattma/gulp-handlebars/tree/master/examples/ember-htmlbars) on how to use the `gulp-handlebars` with latest handlebar#2.0.0

**Comment by lazd** [comment]
Apparently `ember-handlebars` is gone, so I've removed it from examples.
