### ISSUE TITLE
Templates override eachother

### ISSUE THREAD

**Issue by jisaacks** [lazd/gulp-handlebars#46]
If you have templates with the same name (different path) they will override each other.

For example if I have a template in `templates/foo/view.hbs` and in `templates/bar/view.hbs` they will override eachother because only the file __name__ is used when adding the methods to the template namespace. (e.g. `this["templates"]["product"] = ...`)

There should be a way to tell it to use the file path so it would be like  `this["templates"]["foo/product"] = ...` so they would not override each other. This is how [JST](https://github.com/sstephenson/sprockets#javascript-templating-with-ejs-and-eco) does it.

**Comment by lazd** [comment]
See the [namespaceByDirectory example](examples/namespaceByDirectory) if you'd like to compile templates with a mapping that looks like this:

| File path                       | Namespace path             |
| ------------------------------- | -------------------------- |
| source/templates/App.hbs        | MyApp.templates.App        |
| source/templates/App/header.hbs | MyApp.templates.App.header |
| source/templates/App/footer.hbs | MyApp.templates.App.footer |
| source/templates/Other.item.hbs | MyApp.templates.Other.item |

**Comment by jisaacks** [comment]
Makes sense. Thanks! :)

**Comment by lazd** [comment]
You're welcome! Please post back your gulp task after you have it working as desired so others can copy/paste it.
