### ISSUE TITLE
gulp-define-module require by option

### ISSUE THREAD

**Issue by JesseFarebro** [lazd/gulp-handlebars#50]
I was wondering if you would be open to a pull request where you can set the require option for gulp-define-module. I'm using rendr and Handlebars get passed as a parameter to a function and I don't need this option, there is no way to unset it, passing a blank object for require to gulp-define-module still will take the default that gulp-handlebars sets.

Ex.
```
defineModule({
    require: {}
});
```

Will produce ->

```
    var Handlebars = require('handlebars');
```

Now I could either take up this issue with gulp-handlebars or gulp-define-module but I feel like this shouldn't be the default or at least be able to be removed by option. Let me know, I could have a pull request up for you.

**Comment by lazd** [comment]
Ah, I see what you mean...

Honestly, I think `gulp-define-module` should allow you to override the defaults set by a previous plugin the file stream. @wbyoung, what do you think?

**Comment by JesseFarebro** [comment]
@lazd yes, that would make more sense I'll wait for a reply from @wbyoung before submitting any requests

**Comment by wbyoung** [comment]
I think it makes sense for `gulp-define-module` to support:

```js
defineModule({
    require: {
        Handlebars: null
    }
});
```

I've opened wbyoung/gulp-define-module#10 and will welcome a pull request for this.

**Comment by JesseFarebro** [comment]
I can have one for you tonight. This issue can be closed here now, thanks
all.

**Comment by wbyoung** [comment]
@JesseFarebro awesome, thanks.

**Comment by lazd** [comment]
Sounds great, I'll close this. Thanks @wbyoung and @JesseFarebro!
