### ISSUE TITLE
How to return templates as a string instead of a handlebars template?

### ISSUE THREAD

**Issue by codeofsumit** [lazd/gulp-handlebars#58]
currently

`.pipe(wrap('Handlebars.template(<%= contents %>)'))`

makes the templates available as a handlebars function. To use like: `Templates.cart(data)`.
My problem is that I have to prepopulate the HTML strings with language specific copy. So I just want the HTML string of the templates, compile them myself via handlebars and then execute it with some context like so:

```
var templateString = Templates.cart;
var tplStringWithCopy = insertCopy(templateString);
var hbs = Handlebars.compile(tplStringWithCopy);
var html = hbs(data);
```

any ideas how to accomplish this?

**Comment by lazd** [comment]
You can use a helper for your internationalisn. In any case, your issue isn't with this plugin.
