### ISSUE TITLE
Handlebars 4.0.0

### ISSUE THREAD

**Issue by ghusse** [lazd/gulp-handlebars#61]
Handlebars 4.0.0 is out ! Is it possible to update gulp-handlebars, and update its dependency to the latest version of handlebars?

**Comment by lazd** [comment]
Hey @ghusse, can you try using the method described here https://github.com/lazd/gulp-handlebars#compiling-using-a-specific-handlebars-version to compile with Handlebars 4.0.0 and report back if it works/fails?

**Comment by ghusse** [comment]
Thanks for your quick answer.

My real issue is that gulp-handlebars depends on handlebars 3.0.0 (from its package.json). This version of handlebars itself depends on a vulnerable version of uglify-js.

I have a continuous integration build that checks dependencies against known vunlerabilities. I have builds that fail because of this specific version.

**Comment by lazd** [comment]
Ok, we can definitely release a major version of `gulp-handlebars` that depends on Handlebars 4, but let's validate that it works as-is right now.

**Comment by ghusse** [comment]
How can I help?

**Comment by ptarjan** [comment]
+1 Just ran into this

```
Error: Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 4.0.0) or downgrade your runtime to an older version (>= 2.0.0-beta.1).

**Comment by stbaer** [comment]
+1 from me too

**Comment by lazd** [comment]
@ptjarjan @stbaer please follow the instructions here to use Handlebars 4: https://github.com/lazd/gulp-handlebars#compiling-using-a-specific-handlebars-version

**Comment by JustinMcConnell** [comment]
Works for me using the instructions to compile using a specific handlebars version.

**Comment by aliok** [comment]
It doesn't work with 4.0.3

**Comment by lazd** [comment]
@aliok You're going to have to be a little more specific.

**Comment by aliok** [comment]
Sorry, my bad... It works with the instructions (there was a problem in my Gulp file).

**Comment by creage** [comment]
So, when should we expect the "real" upgrade, without the need of altering our configuration?

**Comment by lazd** [comment]
@creage, I am considering removing the dependency on `handlebars` completely and such that users will be required to include the specific version of handlebars they target as a dependency of their project. In that case, you'll have configure it as such in any case.

The rationale is that it's more responsible to be 100% in control of the version of the build artifact you're using and will, therefore, be aware of the version of the runtime you'll need in your application (many issues have been filed where users were using the wrong version of the runtime). `gulp-handlebars` was designed in this way on purpose so it didn't need to be upgraded when new versions of handlebars were released, but I included handlebars as a dependency so it worked out of the box.

What does everyone think of the above?

**Comment by davidvanvo** [comment]
Followed the instructions and i'm getting the following error:

    Uncaught Error: Unknown template object: function

It's referencing the captureStackTrace method.

**Comment by lazd** [comment]
@davidvanvo You're using the wrong version of the Handlebars runtime on the client side. I mentioned this in my last comment, actually. Many people get confused on this point, and forcing users to include a specific version of handlebars will make them aware that they need the corresponding version of the runtime.

**Comment by davidvanvo** [comment]
@lazd thanks, yeah i figured it out soon after i posted that comment. the documentation was a little unclear at first because it's my first attempt at using handlebars, but it makes sense now. thanks.

**Comment by ericbiewener** [comment]
The instructions worked for me as well.

**Comment by ptarjan** [comment]
@lazd look at the rest of the gulp ecosystem. What do they do? 

From my installation, I have 30 gulp plugins and none of them require side-deps, so using those as bellwethers I'd vote you just keep updating handlebars in lock-step with their releases. If you're trying to avoid that maintenance burden, then again look at the community and see how they do it.

**Comment by AlexPashley** [comment]
I'm trying to get the new version of handlebars (4.0.2) but still get the error;

Uncaught Error: Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 4.0.0) or downgrade your runtime to an older version (>= 2.0.0-beta.1).

I've tried to do the steps mentioned by @lazd with package.json and still don't have any luck. Does the package.json need to be in the root of project folder or within the node_modules?

Also do you I have to install bower? A few people are using this in their examples...?

Sorry if this seems a stupid question.

**Comment by AlexPashley** [comment]
I've managed to get it working (I bet nobody else runs into this issue but ill explain below)

- Uninstalled local version of handlebars then did
- npm install --save-dev handlebars

- Uninstalled gulp-handlebars
- npm install --save-dev gulp-handlebars

- Added a package.json to root and when i installed new node packages it updated json file (didnt know it did that)

**Comment by lazd** [comment]
@AlexPashley looks like you just had the wrong version of Handlebars installed locally. Glad you figured it out!

**Comment by robhadfield** [comment]
I'm struggling with this - I have it working with ^1.3.0 by manually retarding the Handlebars version but how do I specify gulp-handlebars to work with handlebars 4.0.3?

I have the instructions but I would really appreciate an example package.json file as don't understand 'passing it as options.handlebars' - what's the syntax for that?

**Comment by lazd** [comment]
@robhadfield the README shows exactly how to set this up, including an example of the package.json. There are full examples in the `examples/` folder as well, see https://github.com/lazd/gulp-handlebars/tree/master/examples/handlebars2 and replace 2.0 with 4.0.

**Comment by timomayer** [comment]
the 4th bugfixing release of handlebars4 is out now so i thnk its time to get out a new gulp-handlebars version that uses handlebars 4.0.0 out of the box. what so you think?

**Comment by barbalex** [comment]
ran into this issue with handlebars 4.0.4 but could solve it with your link to the docs

**Comment by sethjeffery** [comment]
I would also like to see `gulp-handlebars` upgraded to use handlebars 4.0.x.

> The rationale is that it's more responsible to be 100% in control of the version of the build artifact you're using and, if you are, will also aware of the version of the runtime you'll need in your application

Sorry I do not agree with the rationale. Most developers are used to the concept of convention over configuration these days, and would expect that the latest version of gulp-handlebars would be compatible with the latest version of handlebars. It should be on my head to choose an *older* or *worse* configuration, and be prepared for the consequences, but most of the time I should expect to just plug in `gulp-handlebars` and be ready to go.

**Comment by lazd** [comment]
@sethjeffery The responsible thing to do is to provide the exact version of Handlebars you expect, regardless of what the library provides. However, I think we can at least provide the latest version at time of release. In the next version of `gulp-handlebars`, I'll go ahead and link Handlebars@4.x

**Comment by blackfyre** [comment]
In my local version I've overwritten the handlebars dependency to `"handlebars": "^4.0.5"` and everything works as it should :smile:

**Comment by pyrho** [comment]
I confirm instructions from [this](https://github.com/lazd/gulp-handlebars#compiling-using-a-specific-handlebars-version) work with `"handlebars": "^4.0.5"`.

**Comment by ghusse** [comment]
Handlebar dependency in gulp-handlebars is declared as `^3.0.0`, meaning that even if I set a version of `^4.0.5` in my package.json, npm will install a 3.x.x in a subdirectory of gulp-handlebars.

**Comment by graceeunbekim** [comment]
@lazd  "Ok, we can definitely release a major version of gulp-handlebars that depends on Handlebars 4, but let's validate that it works as-is right now." is this confirmed?

The suggestions here works fine but i still need to add `"handlebars":" 4.0.5"` for `devDecependencies` to use `gulp-handlebars` because it's install installing handlebar 3.0.3.
