### ISSUE TITLE
Rendr-handlebars 

### ISSUE THREAD

**Issue by LongJeongS** [lazd/gulp-handlebars#63]
Hi, 
I am trying to use gulp-handlebars in my Rendr project, and I am getting `TypeError: template is not a function`, but it looks like I have the same version of handlebars. 

In my compiled handlebars.js, i see `compiler":[6,">= 2.0.0-beta.1"]` and when i do `npm list | grep handlebars` I see 
```
│ ├─┬ handlebars@2.0.0
├─┬ gulp-handlebars@3.0.1
├─┬ handlebars@2.0.0
├── rendr-handlebars@2.0.1
```

Any idea what might be causing the error ?

**Comment by LongJeongS** [comment]
It looks like I can make it work if I downgrade all the way to `gulp-handlebars: ~1.0.2` and `rendr-handlebars: 0.2.0`

**Comment by lazd** [comment]
You're using the wrong version of Handlebars.

See the [section of the README that shows you how to use a specific version of Handlebars](https://github.com/lazd/gulp-handlebars#compiling-using-a-specific-handlebars-version);

**Comment by LongJeongS** [comment]
Hi @lazd, I have followed that readme, my gulpfile looks like this 

```
    return gulp.src('./app/templates/**/[!__]*.hbs')
        .pipe(plumber())
        .pipe(handlebars({ wrapped : true, handlebars: require('handlebars') }))
        .pipe(wrap('templates["<%= file.relative.replace(/\\\\/g, "/").replace(/.js$/, "") %>"] = <%= file.contents %>;\n'))
        .pipe(concat('compiledTemplates.js'))
        .pipe(wrap('module.exports = function(Handlebars){\ntemplates = {};\n<%= contents %>\nreturn templates \n};'))
        .pipe(gulp.dest('app/templates/'));
```
and I still can't get it to work

**Comment by lazd** [comment]
Add this into your `gulpfile.js`:

```js
console.log(require('handlebars').VERSION);
```

What does it output?

**Comment by LongJeongS** [comment]
I am getting `2.0.0`

**Comment by lazd** [comment]
Great, now check the runtime you're using on the client side. It's not 2.x.

**Comment by LongJeongS** [comment]
yeah looks like it was some wonky stuff going on with rendr-handlebars, thanks for your help.

**Comment by lazd** [comment]
You're welcome, sometimes it's hard to troubleshoot this with the version mismatch between client and build, but I knew right away it was a runtime mismatch as I've had several other users report this.
