### ISSUE TITLE
How do I pass compiler options to handlebar compilers

### ISSUE THREAD

**Issue by adithyan** [lazd/gulp-handlebars#67]
It seems to take no effect,
I'm using handelbars 4.0.5

>gulp.task('templates', () => {	// no i18n
	return gulp.src('src/**/*.hbs')	// no i18n
        .pipe(handlebars({
        	handlebars: require('handlebars'),
        	compilerOptions: {
        		'known': ['i18n', 'ifvalue', 'compare', 'capitaliseFirstLetter', 'link-to'],
        		'knownOnly': true
        	}
        }))
        .pipe(gulp.dest('js'));	// no i18n
});

Am I missing something

**Comment by lazd** [comment]
http://handlebarsjs.com/reference.html

* `knownHelpers`: Hash containing list of helpers that are known to exist (truthy) at template execution time. Passing this allows the compiler to optimize a number of cases. Builtin helpers are automatically included in this list and may be omitted by setting that value to false.

* `knownHelpersOnly`: Set to true to allow further optimzations based on the known helpers list.
