### ISSUE TITLE
Mismatching version compiler/runtime?

### ISSUE THREAD

**Issue by blaasvaer** [lazd/gulp-handlebars#69]
This is what gets compiled from gulp-handlebars. And even JSHint says it's missing a semicolon:
this["Elevator"] = this["Elevator"] || {};
this["Elevator"]["templates"] = this["Elevator"]["templates"] || {};
this["Elevator"]["templates"]["floorlevel"] = Handlebars.template{"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div class=\"floor-level\" data-floor-level=\"\">\n <span class=\"floor-level-number\"></span>\n    <img src=\"assets/images/floor_level.png\" alt=\"Floor Level\" />\n</div>\n";
},"useData":true};
this["Elevator"]["templates"]["floorlevelbutton"] = Handlebars.template{"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "    <a class=\"floor-level-button\" href=\"#\" data-floor-level=\"\"></a>\n";
},"useData":true};

Why is the compiler broken, and how do I fix it?

I've taken the runtime from the node_modules folder, so I don't get why this would not work ...

**Comment by maxkoryukov** [comment]
Looks, like your question is related to the [handlebars compiler itself](https://www.npmjs.com/package/handlebars), and the problem lies out of this plugin

**Comment by maxkoryukov** [comment]
@blaasvaer, Looks, like your question is related to the [handlebars compiler itself](https://www.npmjs.com/package/handlebars), and the problem lies out of this plugin
