### ISSUE TITLE
gulp-wrap 0.12.0 breaks the example under "Compiling using a specific Handlebars version"

### ISSUE THREAD

**Issue by qodesmith** [lazd/gulp-handlebars#74]
I've been using `gulp-handlebars` 4.0.0, `handlebars` 4.0.5, and `gulp-wrap` 0.11.0, all working fine with the example you guys give under the _"Compiling using a specific Handlebars version"_ section. I started a new project  which installed `gulp-wrap` 0.12.0 and was getting a `tmpl is not a function` error thrown from gulp-wrap. Rolling back to 0.11.0 did the trick. I know that this isn't the `gulp-wrap` repo, but at least I thought I'd make the team aware.

**Comment by lazd** [comment]
Thanks for the report @qodesmith, can you paste the full stack trace please for reference?

**Comment by qodesmith** [comment]
@lazd Here's the error I get, copy/pasted straight from the console:

```
{ [TypeError: tmpl is not a function]
  name: 'TypeError',
  message: 'tmpl is not a function',
  stack: 'TypeError: tmpl is not a function\n
    at /Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/consolidate/lib/consolidate.js:779:16\n
    at /Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/consolidate/lib/consolidate.js:143:5\n
    at Promise._execute (/Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/bluebird/js/release/debuggability.js:272:9)\n
    at Promise._resolveFromExecutor (/Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/bluebird/js/release/promise.js:473:18)\n
    at new Promise (/Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/bluebird/js/release/promise.js:77:14)\n
    at promisify (/Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/consolidate/lib/consolidate.js:136:10)\n
    at Function.exports.lodash.render (/Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/consolidate/lib/consolidate.js:775:10)\n
    at /Users/aaron.cordova/Projects/Sandbox/walmart-search/node_modules/gulp-wrap/index.js:73:37\n
    at process._tickCallback (node.js:401:9)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-wrap' }
```

**Comment by lazd** [comment]
Can you provide your gulpfile? Seems like a `gulp-wrap` problem. Does downgrading fix it?

**Comment by qodesmith** [comment]
The entire gulp file is a bit long, so I've provided below the handlebars task and the custom error function I'm using. And yes, downgrading `gulp-wrap` to 0.11.0 resolved the issue.
```
gulp.task('handlebars', function() {
  return gulp.src('dev/templates/**/*.hbs')
    .pipe(handlebars({
      handlebars: require('handlebars')
    }))
    .on('error', onError)
    .pipe(wrap('Handlebars.template(<%= contents %>)'))
    .on('error', onError)
    .pipe(declare({
      root: 'App.templates',
      noRedeclare: true
    }))
    .on('error', onError)
    .pipe(concat('templates.js'))
    .pipe(gulp.dest('dev/js'));
});

function onError(err) {
  console.log(err);
  this.emit('end');
}
```

**Comment by lazd** [comment]
Can you file against `gulp-wrap`? Sounds like an issue there.

If you remove the `handlebars()` call from the pipeline, does the error still happen?

**Comment by qodesmith** [comment]
Just tried removing the `handlebars()` portion no luck. I'll head over to the `gulp-wrap` repo and let them know.

**Comment by qodesmith** [comment]
For any onlookers, I [raised an issue](https://github.com/adamayres/gulp-wrap/issues/28) over at the `gulp-wrap` repo.

**Comment by lazd** [comment]
Ok, so you removed `handlebars()` when using `gulp-wrap` 0.12.0 and still got the error. Therefore, it seems `gulp-handlebars` is not involved with this error at all. If you agree, let's go ahead and close this issue.
