### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by venkateshparuchuri** [lazd/gulp-handlebars#75]
i am reading parent file value in hbs.while doing this iam getting this error
ex: data-product-id="{{../product_id}}"

**Comment by lazd** [comment]
This doesn't have anything to do with compilation.

**Comment by venkateshparuchuri** [comment]
{{#each products}}
    <tr class="card" data-id="{{product_id}}">
        <td>{{itemName}}</td>
        {{#each timesanddata}}
        <td class="form-group">
            <input type="number" class="form-control js-product-waste-entry" data-id="{{../product_id}}">
        </td>
        {{/each}}
    </tr>
    {{/each}}

Passing data is :
    Product: {
	itemName: "Sausage, Egg, & Cheese Biscuit",
	product_availability_id: 1,
	product_id: 1,
	timesanddata: [{
		report_before: 6 am,
		status: true
	} {
		report_before: 8 am,
		status: true
	} {
		report_before: 9 am,
		status: true
	} {
		report_before: 10 am,
		status: true
	} {
		report_before: 11 am,
		status: true
	}

output: "Cannot read property '1' of undefined"

**Comment by Denny966** [comment]
Got the same problem, did you find any solution?

**Comment by Denny966** [comment]
I think I fixed it using partials, there is something weird going on when using ../ in {{#with}} or {{#each}}
