### ISSUE TITLE
Inline partials - parse error

### ISSUE THREAD

**Issue by dimti** [lazd/gulp-handlebars#76]
"gulp-handlebars": "^4.0.0"

```
{{#*inline "cartItemPrice"}}
<div>
    <div class="cart-item-price">
        {{#if price}}
            <span>{{price_formatted}}</span><br>
        {{/if}}
        {{order_price_formatted}}
    </div>
</div>
{{/inline}}

{{> cartItemPrice}}
```

And after execute gulp task: gulp templates
i fetched error:

```
[00:52:22] Starting 'templates'...
[00:52:22] Finished 'templates' after 52 ms

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Parse error on line 1:
{{#*inline "cartItemPri
---^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
```

And my IDE highlight my syntax by red color (some wrong)

But in documentation say about inline partial - it that

http://stackoverflow.com/questions/32336682/handlebars-mustache-missing-helper-partial

https://www.sitepoint.com/using-inline-partials-and-decorators-with-handlebars-4-0/

http://handlebarsjs.com/partials.html

How to correct way to use inline partials?

**Comment by lazd** [comment]
Make sure to pass handlebars 4.0.0 if you want to use features from it. `gulp-handlebars` installs 3.0.0 currently.

See https://github.com/lazd/gulp-handlebars#compiling-using-a-specific-handlebars-version
