### ISSUE TITLE
Precompile loses expressions 

### ISSUE THREAD

**Issue by methodbox** [lazd/gulp-handlebars#77]
I am precompiling templates, which mostly works except one critical function: expressions are returns as empty space.

It would appear either gulp-handlebars is not compatible with handlebars 4.0.5 or its improperly evaluating expressions rather than passing them as-is to the rendered template.

These means dynamic data is not longer rendered.

For example, if I have a template like this:

```
<p>This is my template named {{templateName}}</p>
```

...after the precompile I pull in my script for the templates and this is what is rendered:

`This is my template named`

Checking the DOM the "p" tags are rendered, too. Even though I'm passing the value for the `templateName` nothing is shown. Doing this without a precompile works fine.

If use an HTML escape with three brackets or a backslash, it will render the raw text like `{{{templateName}}}` which is also wrong.

**Comment by lazd** [comment]
Try passing `{ handlebars: require('handlebars') }` to the plugin (see README) and making sure you did a `npm install handlebars@4.0.5`

**Comment by methodbox** [comment]
Thanks, I'll try that in the morning.

**Comment by lazd** [comment]
Closed for inactivity. For those that fine this issue, please look at https://github.com/lazd/gulp-handlebars#version-mismatch-error
