### ISSUE TITLE
Please, provide example of how to have matching compiler and runtime versions of this.

### ISSUE THREAD

**Issue by blaasvaer** [lazd/gulp-handlebars#79]
I've spent the major part of the day already trying to get the right runtime version to match the compiler version as I keep getting »s is undefined yada yade errors« due to a mismatch of versions.

I used to be able to go into the node_modules/gulp-handlebars/ ... dist and pick the right runtime version. If something didn't work I'd go into the handlebars corresponding version. But now, all of a sudden, I can't seem to get ANY version working.

Has something drastically changed?

And how - in a simple way - can I make sure that I have the right handlebars runtime version with the current handlebars compiler?

Please, provide a complete example, as I seem to be guessing to much. : )

**Comment by lazd** [comment]
You can choose whatever version you like. Install the version of handlebars you want to use on the client side with `npm install handlebars@4.0.0`, then pass it in options`{ handlebars: require('handlebars') }`. This is already documented in the readme.

Personally, I didn't want to bundle a version of handlebars at all with this plugin and want users to provide their own version at all times to avoid this confusion.

**Comment by ntziolis** [comment]
While there is documentation around this, it is not clear that require('handlebars'), will pick up the version from the dependencies. While people should know that this is what happens in node, it would make sense to call this out more clearly.

**Comment by lazd** [comment]
@ntziolis I still think the answer to this problem is to NOT install handlebars at all for the user, and require them to `npm install` exactly what version they need. This prevents the mismatch between runtime and compiler, and because the user has installed handlebars themselves and it's a module they must require, it's very clear what's going on.
