### ISSUE TITLE
gulp handlebars save and auto-inject into browsers

### ISSUE THREAD

**Issue by venkateshparuchuri8** [lazd/gulp-handlebars#81]
If i have changed the .hbs files and i want that changes to be reflected in the browser.so for that i am re running  the gulp server then that changes are reflected in browser .please provide the solution with out re running the gulp server the  changes must be reflect to browser.

My code snippet is:
```gulp.task('templates', function(){
  gulp.src('public/views/*.hbs')
    .pipe(handlebars())
    .pipe(wrap('Handlebars.template(<%= contents %>)'))
    .pipe(declare({
      namespace: 'MyApp.templates',
      noRedeclare: true, // Avoid duplicate declarations
    }))
    .pipe(concat('templates.js'))
    .pipe(gulp.dest('build/js/'));
    .pipe(browserSync.stream());
});```

this is not working for me

**Comment by lazd** [comment]
Perhaps it's a problem with "browserSync," I've never used it before and it's outside of the scope of this plugin - this plugin only writes files, it doesn't refresh your browser or so anything downstream. I'm going to close this issue for now.
