### ISSUE TITLE
use handlebars 4.0

### ISSUE THREAD

**Issue by yaodingyd** [lazd/gulp-handlebars#84]
Could you publish a new version with handlebars 4.0? Thank you!

**Comment by lazd** [comment]
https://github.com/lazd/gulp-handlebars#compiling-using-a-specific-handlebars-version

**Comment by yaodingyd** [comment]
@lazd  Thank you very much! My bad for not reading manual...

**Comment by lazd** [comment]
@yaodingyd no problem, I think that we should remove Handlebars as a dependency and require that users provide their own Handlebars version, this will help eliminate confusion on different runtime versions, cause users to be completely in control of their versioning, and eliminate the confusing issue we're discussing right now :)

**Comment by yaodingyd** [comment]
@lazd Again, thanks! I now feel kind of contributing if my stupid oversight could help future users. Thanks!

**Comment by lazd** [comment]
@yaodingyd Make no mistake -- filing issues, commenting, and adding your +1 to an issue is a contribution, even if there's an obvious answer :)

**Comment by yaodingyd** [comment]
@lazd Thanks for your patient and detailed response! I feel like I need to buy you a beer
