### ISSUE TITLE
Reverse block templates error out

### ISSUE THREAD

**Issue by twaffl3s** [lazd/gulp-handlebars#86]
[Based on the format in the gray box](http://handlebarsjs.com/partials.html#partial-block)

Currently, reverse partials (what I call them) where your layout is the partial gives the following error: 
```Error: Parse error on line 1:
{{#> layout }}  <h2>Do
---^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'```

**Comment by lazd** [comment]
Perhaps you're using the wrong handlebars version. See the `handlebars` option in the README.

In any case, a compiler error means this issue is not with gulp-handlebars.
