### ISSUE TITLE
Deprecated libs and vunerability detected

### ISSUE THREAD

**Issue by wbotelhos** [lazd/gulp-handlebars#87]
Hi,

We have vunerability on `uglify-js` that is dependency of `handlebars 3.x`.
I tried update, but lib `ember-handlebars` is not found anymore.

Is this project still mantained?
Any idea when you will have time to update it?

Thank you for the great work.

**Comment by lazd** [comment]
It seems that even the latest version of handlebars 4.0.11 relies on an old version of uglify. That said, it looks like[this as-yet-unreleased commit](https://github.com/wycats/handlebars.js/commit/d3d39423a3ad138b11d039a498ca8c135635e128) fixes that.

**Comment by wbotelhos** [comment]
Thanks for the information and the last update to v5.0.0. <3
