### ISSUE TITLE
Extension-changing broken with gulp@3.x

### ISSUE THREAD

**Issue by spencer-brown** [lazd/gulp-handlebars#89]
The change made in https://github.com/lazd/gulp-handlebars/commit/5a2b0fc9db1554b51583420f0d2645f5413ec1ba made `gulp-handlebars` incompatible with 3.x versions of `gulp`, which don't support `vinyl`'s `extname` property.

The `extname` property [was introduced](https://github.com/gulpjs/vinyl/commit/57b770cbfbf07afca8859b8955ec769e44c1983b#diff-168726dbe96b3ce427e7fedce31bb0bcR184) in `vinyl@2.1.0` but 3.x versions of gulp [use](https://github.com/gulpjs/gulp/blob/v3.9.1/package.json#L41), at latest, `vinyl-fs@^0.3.0` which  [uses](https://github.com/gulpjs/vinyl-fs/blob/v0.3.14/package.json#L21) `vinyl@^0.4.0`.

[Here's](https://github.com/spencer-brown/gulp-handlebars-bug-demo) a repo demonstrating this issue w/ testing instructions.

---

Ultimately, this issue is breaking our partial registration, which is based on y'alls example and [depends on partials having a `.js` file extension](https://github.com/lazd/gulp-handlebars/blob/master/examples/partials/gulpfile.js#L20)

**Comment by spencer-brown** [comment]
cc @lazd

**Comment by lazd** [comment]
Published as 5.0.1
