### ISSUE TITLE
Absent filenames after pipe with gulp-handlebars

### ISSUE THREAD

**Issue by satfx** [lazd/gulp-handlebars#91]
I'm trying to use this package, but faced with strange issue when using v5.0.1 on Windows 10 with Visual Studio (at least with 2015 Pro version). Btw, it is all fine with version <= 5.0.0 on Win10, and with any version on Win7.

As a template precompile task, I'm using exactly the same code what was published as an "partials" example. And when I use it with environment described above, I get a result with no template name. For example,

`Handlebars.registerPartial("", Handlebars.template(...))`
instead of
`Handlebars.registerPartial("Currency", Handlebars.template(...))`
for partials

and

`this["App"]["templates"] = Handlebars.template(...)`
instead of
`this["App"]["templates"]["JelectCheckboxOption"] = Handlebars.template(...)`
for templates.

When adding
`.pipe(print(function (v) { console.log(JSON.stringify(v)); }))`
just after
`.pipe(handlebars())`
I see logged paths without filenames on Win10 with v5.0.1 ("print" is gulp-print package). When making all the same on different gulp-handlebars versions and/or Win OS versions, I can clearly see paths with filenames.

Don't know if it helps, but when calling
`.on("data", function (v) { console.log(JSON.stringify(v)); })`
just after
`.pipe(handlebars())`
the only difference is in absence of `extname` property and in contents of `history` property:

Win7
{
	"history":["C:\\Projects\\TestProject\\templates\\_Currency.hbs"],
	"extname":".js",
	...
}

Win10
{
	"history":["C:\\Projects\\TestProject\\templates\\_Currency.hbs","C:\\Projects\\TestProject\\templates\\"],
	...
}

**Comment by c4rbon-c0py** [comment]
Also experienced this problem. Had to revert back to 5.0.0.

**Comment by lazd** [comment]
A fix has been released as `5.0.2`, @c4rbon-c0py @satfx can you please test?

**Comment by c4rbon-c0py** [comment]
@lazd  Just updated. Everything seems tip-top. I'll report back if I notice anything.

Thanks for the fix!
